### ISSUE TITLE
Appreciation!

### ISSUE THREAD

**Issue by davidhov** [memsharded/test_nats#1]
Thank you very much for your help! Everything worked for me. The only thing I had to change is the following line:
        self.requires("openssl/[>1 <4]")
In my case I have got some error that's why I specified the exact version.
But this is not a big issue and after reading some conan documents probably I can identify the issue (probably depends on my conan version)

**Comment by memsharded** [comment]
That is great, thanks very much for telling!

> In my case I have got some error that's why I specified the exact version.

Sure, no problem, do not hesitate to create issues in https://github.com/conan-io/conan/issues for any further question you might have. Thanks!
